CREATE DATABASE user1_db;
CREATE ROLE user1 WITH LOGIN PASSWORD 'user1pass';
GRANT ALL PRIVILEGES ON DATABASE user1_db TO user1;

CREATE DATABASE user2_db;
CREATE ROLE user2 WITH LOGIN PASSWORD 'user2pass';
GRANT ALL PRIVILEGES ON DATABASE user2_db TO user2;

